# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-22 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0004_bihin_bihin_sts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bihin',
            name='bihin_sts',
            field=models.IntegerField(choices=[(0, '保管棚'), (1, '貸出中'), (2, '廃棄')], verbose_name='状態'),
        ),
    ]
