# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-23 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0006_bihin_bihin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihin',
            name='bihin_shisan',
            field=models.IntegerField(choices=[(0, '購入品'), (1, 'リース')], default=0, verbose_name='資産'),
            preserve_default=False,
        ),
    ]
