# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-23 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0007_bihin_bihin_shisan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihin',
            name='bihin_manufct',
            field=models.CharField(default=0, max_length=255, verbose_name='メーカー'),
            preserve_default=False,
        ),
    ]
