# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-23 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0010_remove_bihin_bihin_rdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihin',
            name='bihin_use',
            field=models.CharField(default=0, max_length=255, verbose_name='使用者'),
            preserve_default=False,
        ),
    ]
